name: Continuous Integration

on: [push, pull_request]

jobs:
  build:
    name: ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: false
      matrix:
        config:
        - name: Visual Studio
          os: windows-2022
        - name: macOS
          os: macos-12
        - name: Linux
          os: ubuntu-22.04

    steps:
    - uses: actions/checkout@v3

    - name: Install Dependencies
      shell: bash
      run: |
        if [[ "${{ runner.os }}" == 'Linux' ]]; then
          sudo apt update && sudo apt install libasound2-dev libfluidsynth-dev libmpg123-dev libsndfile1-dev
        elif [[ "${{ runner.os }}" == 'macOS' ]]; then
          brew install fluidsynth mpg123 libsndfile
        fi

    - name: Configure
      shell: bash
      run: |
        cmake -B build -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=../build_install ..

    - name: Build
      shell: bash
      run: |
        export MAKEFLAGS=--keep-going
        cmake --build build --config Release --parallel 3

    - name: Upload Build Directory
      uses: actions/upload-artifact@v1
      with:
        path: build
        name: ${{ matrix.config.name }}
